---
abstract: 'A Logging Role for Moose based on Log::Log4perl'
author:
  - 'Roland Lammel <lammel@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.57
  IO::Scalar: 0
  Moose: 0.65
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Log-Log4perl
no_index:
  directory:
    - inc
    - t
recommends:
  Moose: 0.65
requires:
  Any::Moose: 0.12
  Log::Log4perl: 1.13
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lammel/moosex-log-log4perl
version: 0.46
